/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'docs-pages': DocsPage;
    'kb-articles': KbArticle;
    'discord-users': DiscordUser;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'docs-pages': DocsPagesSelect<false> | DocsPagesSelect<true>;
    'kb-articles': KbArticlesSelect<false> | KbArticlesSelect<true>;
    'discord-users': DiscordUsersSelect<false> | DiscordUsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-pages".
 */
export interface DocsPage {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g., "getting-started")
   */
  slug: string;
  /**
   * Markdown content
   */
  content: string;
  /**
   * Documentation category
   */
  category?: ('documentation' | 'installing' | 'interface' | 'creator-studio' | 'modules' | 'articles') | null;
  /**
   * Order within category (lower = first)
   */
  sortOrder?: number | null;
  /**
   * Original URL from official docs
   */
  originalUrl?: string | null;
  /**
   * Path in GitHub repo for back-sync
   */
  githubPath?: string | null;
  /**
   * Related KB articles
   */
  relatedKB?: (number | KbArticle)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-articles".
 */
export interface KbArticle {
  id: number;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Markdown content
   */
  content: string;
  type?: ('qa' | 'troubleshooting' | 'tip' | 'reference') | null;
  category?:
    | (
        | 'configuration'
        | 'troubleshooting'
        | 'integrations'
        | 'setup'
        | 'scripting'
        | 'llm'
        | 'performance'
        | 'characters'
        | 'scenarios'
        | 'chat'
        | 'events'
        | 'flags'
      )
    | null;
  /**
   * Topic tags
   */
  topics?:
    | {
        topic?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Search keywords
   */
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Confidence score (0-1)
   */
  confidence?: number | null;
  /**
   * Original contributor name from Discord
   */
  contributor?: string | null;
  /**
   * Linked Discord user who originally contributed
   */
  originalContributor?: (number | null) | DiscordUser;
  /**
   * Discord user who last edited this article
   */
  lastEditedBy?: (number | null) | DiscordUser;
  /**
   * Name of last editor (for display)
   */
  lastEditedByName?: string | null;
  /**
   * When the article was last edited
   */
  lastEditedAt?: string | null;
  /**
   * History of edits
   */
  editHistory?:
    | {
        editor?: (number | null) | DiscordUser;
        editorName?: string | null;
        editedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Path in GitHub repo for back-sync
   */
  githubPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-users".
 */
export interface DiscordUser {
  id: number;
  /**
   * Discord user ID
   */
  discordId: string;
  /**
   * Discord username
   */
  username: string;
  /**
   * Display name (global_name or username)
   */
  displayName: string;
  /**
   * Discord avatar URL
   */
  avatar?: string | null;
  /**
   * Contributor names this user has claimed from KB articles
   */
  claimedContributorNames?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Number of KB edits made
   */
  editCount?: number | null;
  /**
   * Last login time
   */
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'docs-pages';
        value: number | DocsPage;
      } | null)
    | ({
        relationTo: 'kb-articles';
        value: number | KbArticle;
      } | null)
    | ({
        relationTo: 'discord-users';
        value: number | DiscordUser;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-pages_select".
 */
export interface DocsPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  category?: T;
  sortOrder?: T;
  originalUrl?: T;
  githubPath?: T;
  relatedKB?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kb-articles_select".
 */
export interface KbArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  type?: T;
  category?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  confidence?: T;
  contributor?: T;
  originalContributor?: T;
  lastEditedBy?: T;
  lastEditedByName?: T;
  lastEditedAt?: T;
  editHistory?:
    | T
    | {
        editor?: T;
        editorName?: T;
        editedAt?: T;
        id?: T;
      };
  githubPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-users_select".
 */
export interface DiscordUsersSelect<T extends boolean = true> {
  discordId?: T;
  username?: T;
  displayName?: T;
  avatar?: T;
  claimedContributorNames?:
    | T
    | {
        name?: T;
        id?: T;
      };
  editCount?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}